# Generated by Django 4.1.13 on 2024-07-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driver_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='fleet',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
