# Generated by Django 4.1.13 on 2024-07-15 13:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_supervisor_owner_driver'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supervisor',
            managers=[
                ('supervisors', django.db.models.manager.Manager()),
            ],
        ),
    ]
