# Generated by Django 4.1.13 on 2024-08-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_fleet_supervisor'),
        ('accounts', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='fleet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_supervisors', to='fleet.fleet'),
        ),
    ]
