# Generated by Django 4.1.13 on 2024-07-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='supervisor',
        ),
    ]
