# Generated by Django 4.1.13 on 2024-03-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='Name',
            field=models.CharField(default='Other/Ander', max_length=200),
        ),
    ]
