# Generated by Django 4.1.13 on 2024-05-09 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_alter_transaction_date_alter_transaction_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='fleet',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fleet',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_fleets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='transactions.brand'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_transactions', to='transactions.brand'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fleet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_transactions', to='transactions.fleet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_transactions', to='transactions.merchant'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['client', 'fleet'], name='transaction_client__c21a05_idx'),
        ),
    ]
