# Generated by Django 4.1.13 on 2024-07-04 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_alter_transaction_managers_transaction_odo_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='addedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
