# Generated by Django 4.1.13 on 2024-07-04 15:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_addedby'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fleet',
            managers=[
                ('fleets', django.db.models.manager.Manager()),
            ],
        ),
    ]
