# Generated by Django 4.1.13 on 2024-07-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_fleet'),
        ('fleet', '0001_initial'),
        ('transactions', '0008_alter_fleet_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fleet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_transactions', to='fleet.fleet'),
        ),
        migrations.DeleteModel(
            name='Fleet',
        ),
    ]
