# Generated by Django 4.1.13 on 2024-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_fleet_delete_fleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
