# Generated by Django 4.1.13 on 2024-07-16 12:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_brand_fleet_merchant_fleet'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='brand',
            managers=[
                ('brands', django.db.models.manager.Manager()),
            ],
        ),
    ]
