# Generated by Django 4.1.13 on 2024-07-19 08:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_merchant_address_alter_merchant_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='merchant',
            managers=[
                ('merchants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
