# Generated by Django 4.1.13 on 2024-07-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_area_vehicle_colour_vehicle_litres_limit_and_more'),
        ('transactions', '0014_alter_merchant_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_transactions', to='vehicles.vehicle'),
        ),
    ]
