# Generated by Django 4.1.13 on 2024-07-04 15:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vehicle',
            managers=[
                ('vehicles', django.db.models.manager.Manager()),
            ],
        ),
    ]
