# Generated by Django 4.1.13 on 2024-07-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('vehicles', '0002_alter_vehicle_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_vehicles', to='fleet.fleet'),
        ),
    ]
