# Generated by Django 4.1.13 on 2024-07-15 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0003_alter_vehicle_fleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='addedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
