# Generated by Django 4.1.13 on 2024-07-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_addedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='area',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='litres_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='primary_tank_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='secondary_tank_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
