# Generated by Django 4.1.13 on 2024-08-14 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0005_vehicle_area_vehicle_colour_vehicle_litres_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
